In [1]:
#24/5/24
#This notebook aims to convert GOIDS into a one hot encoded dataframe relating to their original SMILES molecule

import pandas as pd
import numpy as np
#Data import
dataset = pd.read_csv('/Users/james/Documents/Honours/Data/Targetdata/DrugTargets.csv')
smiles = dataset['SMILES'].tolist()
toxvals = dataset['Toxicity_Values'].tolist()
dflist =  list(zip(smiles, toxvals))
df = pd.DataFrame(dflist, columns = ['SMILES', 'Toxicity_Values'])
colnames = dataset.columns
colnames = colnames[2:]
#colnames = colnames.str.replace(r"[()'',]", "", regex=True).tolist()

In [2]:
#These are the CHEMBLids that do not have a corresponding UNIPROT id
exclids = [
'(\'CHEMBL3883328\',)',
'(\'CHEMBL2095194\',)',
'(\'CHEMBL1907595\',)',
'(\'CHEMBL1907601\',)',
'(\'CHEMBL2094108\',)',
'(\'CHEMBL2111432\',)',
'(\'CHEMBL3038482\',)',
'(\'CHEMBL1907604\',)',
'(\'CHEMBL1907603\',)'   
]

In [3]:
#Removes CHEMBLids that do not have uniprot or goids
for ids in exclids:
    for cols in dataset:
        if ids == cols:
            dataset.pop(cols)

In [4]:
#Creates an index of chemblids to be skipped as they where not translated to uniprot or go ids
excindex = []
for ids in exclids:
    loops = 0
    for item in colnames:
        if ids in item:
            excindex.append(loops)
        loops = loops + 1

In [5]:
#Reads in files from a given folder, converting them to a list of GO ids
from pathlib import Path
path = Path('/Users/james/Documents/Honours/Data/Targetdata/goids')

count = 0
goidlist = []
for files in path.iterdir():
    with open(files, 'r') as file:
        goids = file.readlines()
    idlist = []
    for ids in goids:
        idlist.append(ids.strip())
    
    goidlist.append(idlist)

In [6]:
#Creates a list of unique GOids
sublist = []
for items in goidlist:
    for ids in items:
        sublist.append(ids)

uniqids = set(sublist)
uniqids = list(uniqids)

In [7]:
#Creates a 1 hot encoded list of goids mapped to chembl ids
def onehotencoder(uniqids, inputlist):
    newlist = []
    for ids in uniqids:
        if ids in inputlist:
            newlist.append(1)
        else:
            newlist.append(0)
    return newlist

idlist = []
for items in goidlist:
    idlist.append(onehotencoder(uniqids, items))

In [33]:
#Gets rid of tox vals and smiles columns then converts the dataframe to a list of lists
tokeep = dataset.columns[2:]
df = dataset[tokeep]

,"('CHEMBL4768',)","('CHEMBL226',)","('CHEMBL3571',)","('CHEMBL3706',)","('CHEMBL5979',)","('CHEMBL2035',)","('CHEMBL2652',)","('CHEMBL3714079',)","('CHEMBL1968',)","('CHEMBL329',)",...,"('CHEMBL252',)","('CHEMBL1628481',)","('CHEMBL1792',)","('CHEMBL208',)","('CHEMBL2888',)","('CHEMBL3991',)","('CHEMBL228',)","('CHEMBL3776',)","('CHEMBL3108639',)","('CHEMBL325',)"
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13239,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13241,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13242,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [44]:
#Creates a series of lists that contain lists of indexed goids
iter = 0
index_goid_smiles = []
for smile in temp:
    currsmile = []
    loops = 0
    for cels in smile:
        if cels == 1:
            currsmile.append(idlist[loops])
        loops = loops + 1
    
    index_goid_smiles.append(currsmile)

In [70]:
#Creates an array of smiles and goids
finallist = []
for smile in index_goid_smiles:
    goidlist = [sum(values) for values in zip(*index_goid_smiles[0])]
    finallist.append(goidlist)

In [91]:
#converts this array into a dataframe
newdf = pd.DataFrame(finallist, columns=uniqids)
newdf = dataset.iloc[:, :2].join(test)

newdf.to_csv('GOIDdata.csv')

In [1]:
newdf

NameError: name 'newdf' is not defined