In [1]:
#17/8/24 Uses the united Chemopy data and recreates the original 22 Toxric Datasets

import pandas as pd
import os
import numpy as np

targetdata = pd.read_csv('/Users/james/Documents/Honours/Data/Chemopy/United/United_Chemopy.csv')
indexdf = pd.read_csv('/Users/james/Documents/Honours/Data/Unified_SMILES/Unified_SMILES.csv')
index = list(indexdf['SMILES'].values)

In [2]:
targetdata

,Unnamed: 0,Weight,nH,nHal,nHet,nHA,nF,nCl,nBr,nI,...,VSAEstate0,VSAEstate1,VSAEstate2,VSAEstate3,VSAEstate4,VSAEstate5,VSAEstate6,VSAEstate7,VSAEstate8,VSAEstate9
0,0,148.150,4,0,5,10,0,0,0,0,...,0.547454,13.559583,0.000000,1.539352,0.000000,0.000000,3.115231,0.000000,0.0,4.905046
1,1,392.198,16,6,16,28,6,0,0,0,...,79.365588,13.706120,6.623437,3.618548,-4.964313,0.501815,-4.874915,-0.226280,0.0,0.000000
2,2,249.040,7,2,9,16,0,2,0,0,...,0.000000,3.800942,8.238624,11.965103,0.176914,5.134145,0.000000,0.000000,0.0,11.906493
3,3,388.264,21,2,24,30,2,0,0,0,...,26.426309,14.554939,20.051051,2.034770,-1.100900,17.734904,-0.034407,0.000000,0.0,0.000000
4,4,446.378,28,0,28,34,0,0,0,0,...,6.779758,16.071759,20.445076,2.038770,1.029534,19.265172,3.943649,4.134694,0.0,1.458255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17768,17768,264.242,14,0,22,22,0,0,0,0,...,0.000000,0.000000,10.542324,0.000000,0.000000,30.791009,0.000000,0.000000,0.0,0.000000
17769,17769,256.219,12,0,20,21,0,0,0,0,...,5.926524,0.000000,8.160341,2.794728,0.000000,22.045884,0.572523,0.000000,0.0,0.000000
17770,17770,344.288,38,0,25,28,0,0,0,0,...,6.106779,2.250052,11.134212,1.014944,1.587880,12.509769,9.398097,9.331601,0.0,0.000000
17771,17771,1198.811,83,0,64,93,0,0,0,0,...,0.000000,156.460124,57.315297,8.917272,-7.738570,8.377055,7.140454,5.195034,0.0,0.000000
17772,17772,452.356,56,0,26,36,0,0,0,0,...,0.000000,0.000000,49.524523,0.000000,1.800837,0.000000,13.324607,11.683366,0.0,0.000000

In [3]:
#First the original SMILES will be reattached to the PaDEL output dataframe in place of its index for clarity
replacements = []
for item in targetdata['Unnamed: 0']:
    replacements.append(index[item])
    
#the 'replacements' list also acts as an index for future use
#the 'Name' column is then dropped
targetdata['Unnamed: 0'] = replacements

In [6]:
newdata = targetdata.transpose()
newdata = newdata.iloc[1:]
newdata = newdata.transpose()

In [7]:
newdata

,Weight,nH,nHal,nHet,nHA,nF,nCl,nBr,nI,nC,...,VSAEstate0,VSAEstate1,VSAEstate2,VSAEstate3,VSAEstate4,VSAEstate5,VSAEstate6,VSAEstate7,VSAEstate8,VSAEstate9
0,148.15,4,0,5,10,0,0,0,0,5,...,0.547454,13.559583,0.0,1.539352,0.0,0.0,3.115231,0.0,0.0,4.905046
1,392.198,16,6,16,28,6,0,0,0,16,...,79.365588,13.70612,6.623437,3.618548,-4.964313,0.501815,-4.874915,-0.22628,0.0,0.0
2,249.04,7,2,9,16,0,2,0,0,9,...,0.0,3.800942,8.238624,11.965103,0.176914,5.134145,0.0,0.0,0.0,11.906493
3,388.264,21,2,24,30,2,0,0,0,24,...,26.426309,14.554939,20.051051,2.03477,-1.1009,17.734904,-0.034407,0.0,0.0,0.0
4,446.378,28,0,28,34,0,0,0,0,28,...,6.779758,16.071759,20.445076,2.03877,1.029534,19.265172,3.943649,4.134694,0.0,1.458255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17768,264.242,14,0,22,22,0,0,0,0,22,...,0.0,0.0,10.542324,0.0,0.0,30.791009,0.0,0.0,0.0,0.0
17769,256.219,12,0,20,21,0,0,0,0,20,...,5.926524,0.0,8.160341,2.794728,0.0,22.045884,0.572523,0.0,0.0,0.0
17770,344.288,38,0,25,28,0,0,0,0,25,...,6.106779,2.250052,11.134212,1.014944,1.58788,12.509769,9.398097,9.331601,0.0,0.0
17771,1198.811,83,0,64,93,0,0,0,0,64,...,0.0,156.460124,57.315297,8.917272,-7.73857,8.377055,7.140454,5.195034,0.0,0.0
17772,452.356,56,0,26,36,0,0,0,0,26,...,0.0,0.0,49.524523,0.0,1.800837,0.0,13.324607,11.683366,0.0,0.0

In [8]:
datasets = []
index = []
directory = '/Users/james/Documents/Honours/Data/ProcessedRaws/'
namelist = []
smiles = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if 'csv' in filename:
        pathname = directory + file
        df = pd.read_csv(pathname)
        datasets.append(df)
        namelist.append(filename[:-4])
        
framelist = []
for df in datasets:
    smiles = list(df['SMILES'].values)
    temp = pd.DataFrame()
    for smile in smiles:
        loops = 0
        for item in replacements:
            if item == smile:
                temp = pd.concat([temp, newdata.iloc[loops]], axis = 1)
            loops += 1
    framelist.append(temp)

In [9]:
framelist[0]

,0,1,2,3,4,5,6,7,8,9,...,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544
Weight,148.15,392.198,249.04,388.264,446.378,229.162,342.253,154.104,396.32,327.709,...,460.186,400.316,352.272,397.74,362.287,362.287,439.753,482.331,403.311,465.38
nH,4,16,7,21,28,5,27,17,31,17,...,20,23,21,23,24,24,27,35,29,34
nHal,0,6,2,2,0,3,0,0,0,1,...,1,0,0,1,0,0,1,4,1,1
nHet,5,16,9,24,28,8,20,9,28,22,...,22,25,21,23,23,23,25,29,26,27
nHA,10,28,16,30,34,15,27,12,32,25,...,31,32,28,30,29,29,33,37,32,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VSAEstate5,0.0,0.501815,5.134145,17.734904,19.265172,3.897917,6.377731,0.0,26.857699,28.831421,...,10.912944,19.453915,13.35022,17.294801,19.833539,19.636096,12.776628,13.241029,13.726178,13.520743
VSAEstate6,3.115231,-4.874915,0.0,-0.034407,3.943649,-4.676677,10.473845,5.797478,3.034494,5.642989,...,7.220918,6.245779,7.897791,4.4958,4.551878,5.457594,4.340082,-0.196909,9.481959,3.679405
VSAEstate7,0.0,-0.22628,0.0,0.0,4.134694,0.0,0.676726,0.737083,3.869816,0.0,...,1.608133,2.068209,2.113118,2.739536,2.902307,2.351115,5.500209,4.458993,3.850174,4.918677
VSAEstate8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.854189
VSAEstate9,4.905046,0.0,11.906493,0.0,1.458255,1.111616,0.0,0.0,0.0,6.691467,...,3.303629,0.0,0.0,6.057991,0.0,0.0,6.356008,0.0,0.0,0.0

In [10]:
finalist = []
loops = 0
for frame in framelist:
    frame = frame.transpose()
    #frame = frame.loc[:,~frame.columns.duplicated()].copy()
    #frame = frame.loc[~frame.index.duplicated(),:].copy()
    toxvals = (datasets[loops]['Toxicity_Value'].values)
    frame.insert(0, 'Toxicity_Value', toxvals)
    
    finalist.append(frame)
    loops += 1

In [16]:
loops = 0
extension = '_Chemopy.csv'
direc = '/Users/james/Documents/Honours/Data/Chemopy/datasets/'
templist = []
for df in finalist:
    newname = namelist[loops] + extension
    path = direc + newname
    
    df.to_csv(path, index = False)
    loops += 1

In [15]:
namelist = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if 'csv' in filename:
        pathname = directory + file
        df = pd.read_csv(pathname)
        datasets.append(df)
        namelist.append(filename[:-4])